<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$terms= 'These are our terms and conditions (hereinafter referred to as the "User Terms") apply to any use of Trustalyze\'s website, services and or plugins and extension bearing the Trustalyze Confidence System and or TCS (hereinafter referred to as the "Website"). The Website is supplied by Trustalyze, LLC, a Wyoming, US company with offices in Cheyenne, Wyoming and Portland, Oregon. These User Terms are deemed to include all other operating policies, rules and guidelines that are referred to herein or that we may otherwise publish on the Website (as such, policies, rules and guidelines may be amended from time to time), including without limitation: Parties -"You" and "your" refer to you, as a user of the Site. A "user" is someone who accesses, browses, crawls, scrapes, or in any way uses the Site. "We," "us," and "our" refer to Trustalyze and Trustalyze Confidence System and or TCS. Trustalyze is GDPR compliant including handling of data and cookies.';

$terms .=   'Our Privacy Policy

By using the Trustalyze Website, plugins and or extensions bearing the Trustalyze Confidence System and or TCS, you accept to be subject to these User Terms. If you do not accept these User Terms, you are not permitted to use the Website, plugins and extension bearing the Trustalyze Confidence System and or TCS and are kindly requested not to use these any further. The registration as a user requires your express acceptance of these User Terms.
THE TRUSTALYZE SERVICES
1  Registered User
1.1  Trustalyze grants you the non-exclusive, non-transferable, revocable, limited right to access and use the Website, plugins and extension bearing the Trustalyze Confidence System and or TCS. In order to gain full access and use of the Website, you must create a company profile and register as a user (hereinafter referred to as "Registered User"). 1.2  You are only permitted to register one profile per company on the Website. The profile is personal and you must not transfer it to others. 1.3  In order to become a Registered User, you need a password. You choose your own password which must be used with your email address when logging onto the Website. Alternatively, we send the password to you. The password is personal and you must not transfer it or in other ways make it available to others. It is your responsibility to ensure that the password does not fall into the hands of a third party. If you become aware that the password is or may have been compromised, you are obligated to inform us hereof. We can and will change the password if there is a risk that the password has been compromised or is used in violation of the User Terms. 1.4  We are entitled at any time, without notice and without prejudice, to suspend or change your profile in the event of your violation or suspected violation of these User Terms or applicable law. 1.5  You are not permitted to gain access or attempt to gain access to the parts of the Website requiring user registration if you are not a Registered User. 1.6. Some data that you enter in via your registration process is public information where noted in specific registration fields. We place your company name, address, website, email and phone number on your company profile page which is public facing. Company profile pages are permanent and not deleted. If you put in private details and want those changed please email us at contact@trustalyze.com and include new replacement data.
2  User-Generated Content from Registered Users
2.1  You hereby grant us the worldwide, non-exclusive, perpetual, irrevocable, royalty-free right and license to publish, display, reproduce, modify, create derivative works of and commercially exploit any material, information, notifications, reviews, articles or other types of communication or other user generated content, which you create on the Website as a Registered User. We may freely use and transfer the user generated content and disclose the user generated content to third parties. 2.2  Registered Users are liable for the user generated content they publish on the Website. 2.3  Registered Users warrant that all user generated content posted on the Website is correct and true (where they state facts) or genuinely held (where they state opinions). 2.4  User generated content must relate to a company or organization from which the Registered User has purchased or can otherwise document using the company\'s or organization\'s products or services. 2.5  You may not publish user generated content regarding companies to which you have personal or professional relations. 2.6  Registered Users must not, and must not allow any third party to, publish user generated content on the website which

    is of a marketing nature or has marketing purposes,
    is unlawful, deceptive, misleading, fraudulent, threatening, abusive, harassing, libelous, defamatory, wrongful, obscene, pornographic or profane,
    has sexist, political or racial character,
    violates other people\'s rights, including any intellectual property rights, rights of privacy and\or rights of publicity,
    is offensive or in any way breaches any applicable local, national or international law or regulation,
    violates these Terms,
    reveals any personal information about another individual, including another person\'s name, address, phone number, email address, credit card information or any other information that could be used to track, contact or impersonate that person,
    has a disloyal or unlawful purpose and\or content (or promotes unlawful purposes), or
    is technically harmful (including without limitation computer viruses, logic bombs, malware, ransomeware, harmful components, corrupted data or other malicious software, harmful data or conduct).

2.7  Contributors of user generated content warrant in every context that the user generated content is lawful and in compliance with the Terms. If Trustalyze receives notice or otherwise becomes aware that user generated content violates current legislation and\or the User Terms, we may delete the user generated content without any notice, and we - dependent on the character of the violation - may inform the violated party and\or the authorities of the violation. Our right to delete will not be conditioned on an explanation, although we will strive to inform the Registered User about the deletion and the reason hereof. 2.8  The Registered User hereby grants us the right to initiate and take any legal actions which we deem necessary in case of infringement of the Registered User\'s User Generated Content. The Registered User must guarantee to indemnify us for any claims which may be made against us as a consequence of the Registered User\'s violation of the User Terms or current legislation. The Registered User must indemnify and hold us harmless from and against any claim or loss due to third party claims against us resulting from the user generated content of the Registered User. 2.9  We may at any time request information about the user generated content from the Registered User, including documentation supporting the information included in the user generated content, e.g. documentation evidencing that the user generated content is based on an actual buying experience in an actual customer relation to the company to which the user generated content relates.
GENERAL TERMS
3  Rights
3.1  The Website and the services we offer via the Website, including all underlying technology and intellectual property rights embodied therein, are and remain our sole and exclusive property, and no license or any other right is granted to any such underlying technology. If you provide feedback, ideas or suggestions regarding the Website or the services offered on the Website ("Feedback"), we are free to fully exploit such Feedback. 3.2  The content on the Website, including but not limited to the intellectual property rights, text, characteristics, graphics, icons, photos, calculations, references and software is or will be our property or the property of a third party (other than the Registered User) and is protected by U.S. and applicable international legislation, including without limitation applicable copyright and trademark laws. 3.3  Unauthorized copying, distribution, presentation or other use of the Website or part hereof is a violation of U.S. law and may thus result in civil and\or criminal penalties. 3.4  To the fullest extent permitted by law, the rights to free use of the user generated content are transferred to us irrevocably, without any time limitation and without territorial limitations, by submitting the user generated content to us. 3.5  Downloading and other digital copying of the content on the Website or parts hereof are only permitted for personal non-commercial use unless otherwise agreed with us in writing or allowed under applicable mandatory law. 3.6  All company names, trademarks and other business characteristics on the Website is or will be our property or the property of a third party (other than the Registered User) and must only be used for business purposes upon prior approval from us or the third party owner, respectively.
4  Personal data
4.1  We perform different types of processing of personal data in connection with the use of the Website. Please visit our Privacy Policy for more details.
5  Disclaimers
5.1  THE WEBSITE, CONTENT AND SERVICES OFFERED ON THE WEBSITE ARE PROVIDED \'AS IS\' AND AS AVAILABLE WITHOUT REPRESENTATIONS OR WARRANTIES OF ANY KIND. TRUSTALYZE EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION ANY WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. THE WEBSITE AND SERVICES MAY BE MODIFIED, UPDATED, INTERRUPTED, SUSPENDED OR DISCONTINUED AT ANY TIME WITHOUT NOTICE OR LIABILITY. 5.2  We make no representations or warranties with respect to any user generated content published on the Website. 5.3  We disclaim all liability for the content of user generated content. Our non-liability applies, without limitation, to any user generated content. We are not liable for any links to third party websites in the user generated content, including for the content of the page to which the user generated content links. 5.4  Recommendations, reviews, comments, etc. of specific companies, services, e-businesses, etc. on the Website are provided by Registered Users and are not endorsements made by Trustalyze. We disclaim all liability for the content of the Website. The use of our services is in any respect the sole responsibility of the Registered Users. We cannot be held liable for the availability of the Website.
6  Limitation of liability
6.1  WE SHALL IN NO CASE BE HELD LIABLE, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE FOR DAMAGES FOR THE USE OF THE WEBSITE, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING (I) LOSS OF PROFITS, CONTRACTS, TURNOVER, BUSINESS, BUSINESS OPPORTUNITY, LOSS OR CORRUPTION OF DATA OR RECOVERY OF DATA, GOODWILL, SECURITY BREACH RESULTING FROM A FAILURE OF THIRD PARTY TELECOMMUNICATIONS AND\OR THE INTERNET, ANTICIPATED SAVINGS OR REVENUE (REGARDLESS OF WHETHER ANY OF THESE ARE DIRECT, INDIRECT OR CONSEQUENTIAL) (II) ANY LOSS OR DAMAGE ARISING IN CONNECTION WITH LIABILITIES TO THIRD PARTIES (WHETHER DIRECT, INDIRECT OR CONSEQUENTIAL) OR (III) ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL LOSS OR DAMAGE WHATSOEVER. SOME STATES AND OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU. 6.2  OUR TOTAL AGGREGATE LIABILITY, INCLUDING WITHOUT LIMITATION LIABILITY FOR BREACH OF CONTRACT, MISREPRESENTATION (WHETHER WRONGFUL OR STATUTORY), TORT (INCLUDING NEGLIGENCE), BREACH OF STATUTORY DUTY OR OTHERWISE, ARISING FROM OR IN CONNECTION WITH THE USER TERMS, THE WEBSITE OR OUR SERVICES WILL NEVER FOR ANY AND ALL ACTIONABLE CIRCUMSTANCES EXCEED ONE HUNDRED DOLLARS ($100.00). YOU FURTHER AGREE THAT NO CLAIMS OR ACTIONS ARISING OUT OF, OR RELATED TO, THE USE OF OUR WEBSITE OR SERVICES OR THESE USER TERMS MAY BE BROUGHT BY YOU MORE THAN ONE (1) YEAR AFTER THE ACTIONABLE EVENT. NOTHING IN THE USER TERMS EXCLUDES OR LIMITS EITHER PARTY\'S LIABILITY FOR MATTERS WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.
7  Other Terms
7.1  We may at any time, in our sole discretion, revise or change these User Terms. We will make an effort to provide reasonable advance notice of any such changes. We may at any time, in our own discretion and without notice, close, change or reorganize the Website. As a Registered User you accept to be covered by the at all times current User Terms. Any revision or change of the User Terms will be stated on the Website. We will furthermore strive to inform the Registered Users about the change of the User Terms. The Registered Users agree that the continued use of the Website after any posted modified version of the User Terms is an acceptance of the modified User Terms. 7.2  Should any of these Terms be regarded as unlawful or without effect and therefore not to be enforced, this will not have any effect on the applicability and enforcement of the remaining part of the User Terms.
8  Term and termination
8.1 We may terminate your right to access and use the services offered on the Website at any time for any reason without liability. If we do so any rights granted to you herein will immediately cease. Sections 2-10 will survive any termination of the User Terms. 8.2 Our system is designed to catch fake reviews. If your account is flagged due to posting of fake reviews then your account will be terminated and all of your reviews, replies, company profile page will be removed from the Trustalyze system.
9  Applicable law and venue
9.1  The User Terms and the relationship between you and Trustalyze are governed by the laws of the State of Wyoming, without regard to the conflicts of law provisions thereof. Any disputes must be brought exclusively in the state or federal courts located in Wyoming, and the parties hereby consent to the jurisdiction of such courts.
10  Copyright dispute policy
10.1 It is Trustalyze\'s policy to (i) block access to or remove material that it believes in good faith to be copyrighted material that has been illegally copied and distributed by any of our advertisers, affiliates, content providers or members or users; and (ii) remove and discontinue service to repeat offenders. Trustalyze has adopted a policy toward copyright infringement in accordance with the Digital Millennium Copyright Act or DMCA.
11  Miscellaneous
11.1  You acknowledge and agree that these User Terms constitute the complete and exclusive agreement between you and Trustalyze concerning your use of the Website and supersede and govern all prior proposals, agreements or other communications. 11.2  Nothing contained in these User Terms can be construed as creating any agency, partnership or other form of joint enterprise between us. Our failure to require your performance of any provision hereof will not affect our full right to require such performance at any time thereafter, nor may our waiver of a breach of any provision hereof be taken or held to be a waiver of the provision itself. You may not assign any rights granted to you hereunder, and any such attempts are void.
12  CONTACT
12.1  You may contact Trustalyze via email at contact@trustalyze.com or the following mailing address: Trustalyze LLC Attn: Support Team 1604 Capital Street Cheyenne, WY, 82001';